import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/components/shared/NavbarWrapper";

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <NavbarWrapper />
        <div className="min-h-screen ">{children}</div>
      </body>
    </html>
  );
}
